/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CardItemI, } from "./models/card-item";
import { MatchResults, } from "@stencil/router";
export namespace Components {
    interface AppCard {
        "card": CardItemI;
    }
    interface AppCardDetail {
        "card": CardItemI;
    }
    interface AppCards {
        "cards": CardItemI[];
    }
    interface AppDetailPage {
        "match": MatchResults;
    }
    interface AppHeader {
    }
    interface AppIndexPage {
    }
    interface AppNotFoundPage {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppCardElement extends Components.AppCard, HTMLStencilElement {
    }
    var HTMLAppCardElement: {
        prototype: HTMLAppCardElement;
        new (): HTMLAppCardElement;
    };
    interface HTMLAppCardDetailElement extends Components.AppCardDetail, HTMLStencilElement {
    }
    var HTMLAppCardDetailElement: {
        prototype: HTMLAppCardDetailElement;
        new (): HTMLAppCardDetailElement;
    };
    interface HTMLAppCardsElement extends Components.AppCards, HTMLStencilElement {
    }
    var HTMLAppCardsElement: {
        prototype: HTMLAppCardsElement;
        new (): HTMLAppCardsElement;
    };
    interface HTMLAppDetailPageElement extends Components.AppDetailPage, HTMLStencilElement {
    }
    var HTMLAppDetailPageElement: {
        prototype: HTMLAppDetailPageElement;
        new (): HTMLAppDetailPageElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppIndexPageElement extends Components.AppIndexPage, HTMLStencilElement {
    }
    var HTMLAppIndexPageElement: {
        prototype: HTMLAppIndexPageElement;
        new (): HTMLAppIndexPageElement;
    };
    interface HTMLAppNotFoundPageElement extends Components.AppNotFoundPage, HTMLStencilElement {
    }
    var HTMLAppNotFoundPageElement: {
        prototype: HTMLAppNotFoundPageElement;
        new (): HTMLAppNotFoundPageElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-card": HTMLAppCardElement;
        "app-card-detail": HTMLAppCardDetailElement;
        "app-cards": HTMLAppCardsElement;
        "app-detail-page": HTMLAppDetailPageElement;
        "app-header": HTMLAppHeaderElement;
        "app-index-page": HTMLAppIndexPageElement;
        "app-not-found-page": HTMLAppNotFoundPageElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppCard {
        "card"?: CardItemI;
    }
    interface AppCardDetail {
        "card"?: CardItemI;
    }
    interface AppCards {
        "cards"?: CardItemI[];
    }
    interface AppDetailPage {
        "match"?: MatchResults;
    }
    interface AppHeader {
    }
    interface AppIndexPage {
    }
    interface AppNotFoundPage {
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-card": AppCard;
        "app-card-detail": AppCardDetail;
        "app-cards": AppCards;
        "app-detail-page": AppDetailPage;
        "app-header": AppHeader;
        "app-index-page": AppIndexPage;
        "app-not-found-page": AppNotFoundPage;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-card": LocalJSX.AppCard & JSXBase.HTMLAttributes<HTMLAppCardElement>;
            "app-card-detail": LocalJSX.AppCardDetail & JSXBase.HTMLAttributes<HTMLAppCardDetailElement>;
            "app-cards": LocalJSX.AppCards & JSXBase.HTMLAttributes<HTMLAppCardsElement>;
            "app-detail-page": LocalJSX.AppDetailPage & JSXBase.HTMLAttributes<HTMLAppDetailPageElement>;
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-index-page": LocalJSX.AppIndexPage & JSXBase.HTMLAttributes<HTMLAppIndexPageElement>;
            "app-not-found-page": LocalJSX.AppNotFoundPage & JSXBase.HTMLAttributes<HTMLAppNotFoundPageElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
